name: main

on:
  push:
    branches: [main, test-me-*]
  pull_request:

jobs:
  main-latest-git:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.2.0
    with:
      env: '["py37"]'
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.2.0
    with:
      env: '["py38"]'
